set_energy_meter:
  name: Set energy meter
  description: Set the energy meter value and calculate the offset.
  fields:
    entity_id:
      name: Energy Sensor
      description: The energy sensor entity_id
      required: true
      example: sensor.my_meter
      selector:
        entity:
          domain: sensor
    meter_value:
      name: Meter Value
      description: The current real Zählerstand in kWh
      required: true
      example: 1234.5
      selector:
        number:
          min: 0
          max: 999999
          step: 1
          unit_of_measurement: kWh
          mode: box
